import { describe, expect, it } from 'vitest'
import { createStarterDeck, createTutorialDecks } from '../game/cards'
import type { Card } from '../game/types'

const EXPECTED_PLAYER_ONE_STARTER_DECK_2026 = [
  'p1-swamp-4|Swamp|land',
  'p1-island-7|Island|land',
  'p1-forest-7|Forest|land',
  'p1-mountain-0|Mountain|land',
  'p1-mountain-4|Mountain|land',
  'p1-plains-5|Plains|land',
  'p1-swamp-0|Swamp|land',
  'p1-swamp-6|Swamp|land',
  'p1-island-0|Island|land',
  'p1-plains-2|Plains|land',
  'p1-plains-7|Plains|land',
  'p1-forest-4|Forest|land',
  'p1-forest-3|Forest|land',
  'p1-plains-4|Plains|land',
  'p1-island-5|Island|land',
  'p1-forest-9|Forest|land',
  'p1-mountain-8|Mountain|land',
  'p1-plains-8|Plains|land',
  'p1-mountain-5|Mountain|land',
  'p1-plains-3|Plains|land',
  'p1-island-4|Island|land',
  'p1-island-6|Island|land',
  'p1-plains-9|Plains|land',
  'p1-swamp-2|Swamp|land',
  'p1-forest-5|Forest|land',
  'p1-forest-6|Forest|land',
  'p1-swamp-5|Swamp|land',
  'p1-plains-0|Plains|land',
  'p1-island-2|Island|land',
  'p1-plains-6|Plains|land',
  'p1-plains-1|Plains|land',
  'p1-forest-8|Forest|land',
  'p1-swamp-3|Swamp|land',
  'p1-mountain-9|Mountain|land',
  'p1-forest-1|Forest|land',
  'p1-mountain-6|Mountain|land',
  'p1-swamp-8|Swamp|land',
  'p1-island-8|Island|land',
  'p1-mountain-3|Mountain|land',
  'p1-swamp-9|Swamp|land',
  'p1-mountain-2|Mountain|land',
  'p1-swamp-7|Swamp|land',
  'p1-mountain-7|Mountain|land',
  'p1-island-9|Island|land',
  'p1-forest-0|Forest|land',
  'p1-island-3|Island|land',
  'p1-island-1|Island|land',
  'p1-mountain-1|Mountain|land',
  'p1-swamp-1|Swamp|land',
  'p1-forest-2|Forest|land',
] as const

const EXPECTED_TUTORIAL_PLAYER_DECK = [
  'tutorial-p0-island-0|Island|land',
  'tutorial-p0-forest-0|Forest|land',
  'tutorial-p0-mountain-0|Mountain|land',
  'tutorial-p0-swamp-0|Swamp|land',
  'tutorial-p0-plains-0|Plains|land',
  'tutorial-p0-island-1|Island|land',
  'tutorial-p0-forest-1|Forest|land',
  'tutorial-p0-mountain-1|Mountain|land',
  'tutorial-p0-swamp-1|Swamp|land',
  'tutorial-p0-plains-1|Plains|land',
  'tutorial-p0-island-2|Island|land',
  'tutorial-p0-forest-2|Forest|land',
  'tutorial-p0-mountain-2|Mountain|land',
  'tutorial-p0-swamp-2|Swamp|land',
  'tutorial-p0-plains-2|Plains|land',
  'tutorial-p0-island-3|Island|land',
  'tutorial-p0-forest-3|Forest|land',
  'tutorial-p0-mountain-3|Mountain|land',
  'tutorial-p0-swamp-3|Swamp|land',
  'tutorial-p0-plains-3|Plains|land',
  'tutorial-p0-island-4|Island|land',
  'tutorial-p0-forest-4|Forest|land',
  'tutorial-p0-mountain-4|Mountain|land',
  'tutorial-p0-swamp-4|Swamp|land',
  'tutorial-p0-plains-4|Plains|land',
  'tutorial-p0-island-5|Island|land',
  'tutorial-p0-forest-5|Forest|land',
  'tutorial-p0-mountain-5|Mountain|land',
  'tutorial-p0-swamp-5|Swamp|land',
  'tutorial-p0-plains-5|Plains|land',
  'tutorial-p0-island-6|Island|land',
  'tutorial-p0-forest-6|Forest|land',
  'tutorial-p0-mountain-6|Mountain|land',
  'tutorial-p0-swamp-6|Swamp|land',
  'tutorial-p0-plains-6|Plains|land',
  'tutorial-p0-island-7|Island|land',
  'tutorial-p0-forest-7|Forest|land',
  'tutorial-p0-mountain-7|Mountain|land',
  'tutorial-p0-swamp-7|Swamp|land',
  'tutorial-p0-plains-7|Plains|land',
  'tutorial-p0-island-8|Island|land',
  'tutorial-p0-forest-8|Forest|land',
  'tutorial-p0-mountain-8|Mountain|land',
  'tutorial-p0-swamp-8|Swamp|land',
  'tutorial-p0-plains-8|Plains|land',
  'tutorial-p0-island-9|Island|land',
  'tutorial-p0-forest-9|Forest|land',
  'tutorial-p0-mountain-9|Mountain|land',
  'tutorial-p0-swamp-9|Swamp|land',
  'tutorial-p0-plains-9|Plains|land',
] as const

const EXPECTED_TUTORIAL_OPPONENT_DECK = [
  'tutorial-p1-island-0|Island|land',
  'tutorial-p1-plains-0|Plains|land',
  'tutorial-p1-plains-1|Plains|land',
  'tutorial-p1-plains-2|Plains|land',
  'tutorial-p1-plains-3|Plains|land',
  'tutorial-p1-plains-4|Plains|land',
  'tutorial-p1-plains-5|Plains|land',
  'tutorial-p1-plains-6|Plains|land',
  'tutorial-p1-plains-7|Plains|land',
  'tutorial-p1-plains-8|Plains|land',
  'tutorial-p1-plains-9|Plains|land',
  'tutorial-p1-plains-10|Plains|land',
  'tutorial-p1-plains-11|Plains|land',
  'tutorial-p1-plains-12|Plains|land',
  'tutorial-p1-plains-13|Plains|land',
  'tutorial-p1-plains-14|Plains|land',
  'tutorial-p1-plains-15|Plains|land',
  'tutorial-p1-plains-16|Plains|land',
  'tutorial-p1-plains-17|Plains|land',
  'tutorial-p1-plains-18|Plains|land',
  'tutorial-p1-plains-19|Plains|land',
  'tutorial-p1-plains-20|Plains|land',
  'tutorial-p1-plains-21|Plains|land',
  'tutorial-p1-plains-22|Plains|land',
  'tutorial-p1-plains-23|Plains|land',
  'tutorial-p1-plains-24|Plains|land',
  'tutorial-p1-plains-25|Plains|land',
  'tutorial-p1-plains-26|Plains|land',
  'tutorial-p1-plains-27|Plains|land',
  'tutorial-p1-plains-28|Plains|land',
  'tutorial-p1-plains-29|Plains|land',
  'tutorial-p1-plains-30|Plains|land',
  'tutorial-p1-plains-31|Plains|land',
  'tutorial-p1-plains-32|Plains|land',
  'tutorial-p1-plains-33|Plains|land',
  'tutorial-p1-plains-34|Plains|land',
  'tutorial-p1-plains-35|Plains|land',
  'tutorial-p1-plains-36|Plains|land',
  'tutorial-p1-plains-37|Plains|land',
  'tutorial-p1-plains-38|Plains|land',
  'tutorial-p1-plains-39|Plains|land',
  'tutorial-p1-plains-40|Plains|land',
  'tutorial-p1-plains-41|Plains|land',
  'tutorial-p1-plains-42|Plains|land',
  'tutorial-p1-plains-43|Plains|land',
  'tutorial-p1-plains-44|Plains|land',
  'tutorial-p1-plains-45|Plains|land',
  'tutorial-p1-plains-46|Plains|land',
  'tutorial-p1-plains-47|Plains|land',
  'tutorial-p1-plains-48|Plains|land',
] as const

function cardSignatures(cards: readonly Card[]): string[] {
  return cards.map(({ id, name, type }) => `${id}|${name}|${type}`)
}

describe('card deck compatibility', () => {
  it('preserves the complete fixed-seed starter deck order and serialized card fields', () => {
    expect(cardSignatures(createStarterDeck(1, 2026))).toEqual(
      EXPECTED_PLAYER_ONE_STARTER_DECK_2026,
    )
  })

  it('preserves both complete scripted tutorial deck orders and legacy ids', () => {
    const [playerDeck, opponentDeck] = createTutorialDecks()
    expect(cardSignatures(playerDeck)).toEqual(EXPECTED_TUTORIAL_PLAYER_DECK)
    expect(cardSignatures(opponentDeck)).toEqual(EXPECTED_TUTORIAL_OPPONENT_DECK)
  })
})
